### ISSUE TITLE
Not a sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-component-lifecycle-overview#2]
This is not a sentence:
"The initial render and all subsequent re-renders of content."

Suggest combining it with the previous sentence as follows:
"This method is called every time a component renders: the initial render and all subsequent re-renders of content."

Thank you.

**Comment by maxwellbenton** [comment]
Thank you @ValerieHMoore! I've used your suggested replacement to fix this error.
