### ISSUE TITLE
confusing language

### ISSUE THREAD

**Issue by lesliesage** [learn-co-curriculum/react-component-lifecycle-overview#4]
In this portion:

> It is uncommon that we use this hook - even the React documentation mentions that it exists for rare use cases. This method is called every time a component renders. The initial render and all subsequent re-renders of content.

The first and second sentences appear contradictory. Does this mean the method is called but we don't call it? Maybe that could be explained a little better? The third sentence is not a sentence...

**Comment by maxwellbenton** [comment]
Hi @lesliesage,

Thank you for spotting this and opening this issue. We've updated this lesson based on your feedback and added a bit more explanation regarding `static getDerivedStateFromProps` and why we recommend using it sparingly, which we believe resolves this issue.

We apologize for any confusion this may have caused, but we appreciate you taking the time to provide feedback.

Thank you for contributing!
